[metadata]
name = parseandstore
version = attr: parseandstore.__version__
author = Mustapha El KAMILI
classifiers =
	    Programming Language :: Python :: 3.13

[options]
zip_safe = False
include_package_data = True
python_requires = >= 3.13
packages = find:
test_suite = tests
setup_requires =
    pytest-runner >=3.9.2

install_requires =

    colorama >= 0.4.6
    tqdm >= 4.67.1
    python-dotenv >= 1.0.1

    clickhouse-connect >= 0.8.15

    langchain >= 0.3.17
    langchain-community >= 0.3.16
    langchain-core >= 0.3.34
    langchain-ollama >= 0.2.3
    langchain-experimental >= 0.3.4

    llama-parse >= 0.6.1
    llama-index >= 0.12.17
    llama-index-core >= 0.12.17

    llama-index-readers-file >= 0.4.5

    types-tqdm >= 4.67.0.20241221
    types-colorama >= 0.4.15.20240311
    unstructured >= 0.16.20

[options.entry_points]
console_scripts =
    parse_store = parseandstore:start
